:icons: font 

In this module you will participate to complete the implementation of a multi-channel support service for Globex customers that will enable clients to chat in real time with a team of agents.

== Business and Technical Context

As an added initiative to the digital transformation, Globex wants to implement a new, all digital, support service where customers can get instant help from a team of support agents. The goal is to build a pluggable event-driven architecture that allows multiple communication channels and services to integrate with ease to the platform.

[pending] image here

You will be involved in the new hub's first iteration (by completing all the module steps) to complete the integration of two customer facing channels with the agent's system. Customers will be able to choose contacting Globex via its Web portal or via its public space in Slack, available on-line (using a browser), or by installing the app or their devices. Slack is a very popular and widely adopted messaging platform for businesses.

At the other end of the line, the team of agents providing support services for Globex will use Discord as their communication platform. Discord is a well known chat platform, very popular among gamers, but increasingly embraced by enterprises to connect internal teams but also for external interactions with customers as a way to maintain close contact.

[pending] image here

This module showcases how to integrate the service with some of the most popular messaging platforms (Slack & Discord), including Globex's in-house customer communication interface (Web chat widget), using a collection of capabilities all included in Red Hat Application Foundation.


== Technical Capabilities

The key capabilities you will use in this module are:

 - Camel K, the integration tool to create all the processing flows.
 - AMQ Broker, the messaging broker enabling event-based interactions.
 - AMQ Streams (Kafka), to store and replay customer/agent interactions.
 - DataGrid (Cache), to keep the context of interactions context alive.
 - S3 storage, to store conversations.
+
[NOTE]
====
S3 in this workshop is served using Minio for simplicity. Full featured on-premise storage capabilities are provided by OpenShift Data Foundation.
====

== Module exercises


== What is Red Hat build of Apache Camel K?

TODO

[NOTE]
====
A random note
====


== What is Red Hat AMQ Broker?

== What is Red Hat AMQ Streams?

== What is Red Hat AMQ DataGrid?

== What is Red Hat OpenShift Data Foundation?
