:icons: font 

In this module you discover how to build a multi-channel support service for Globex customers that allows clients to chat with a team of agents in real time.

== Business and Technical Context

TODO: expand

As mentioned in the introduction module (TODO: insert link) of the workshop, Globex went through a first modernization phase for their retail web application, moving from a legacy monolith to a containerized application. The Globex retail application runs on OpenShift in the public cloud.
However, for a number of technical and regulatory reasons, the database of the Globex retail application is still running on-premise in one of Globex' data centers.
The challenge for Globex is now to enable the retail application to connect to the database. For obvious reasons, Globex doesn't want to expose the database ove the public internet, so a private, secure link needs to be setup between the OpenShift instance on the public cloud and the Globex data center. 
This can be accomplished with a VPN between the public cloud and the Globex data center. However a VPN can be hard to set up, and requires deep networking expertise. A dedicated layer 7 service network such as Red Hat Service Interconnect on the other hand is a lot easier to set up.

== What is Red Hat build of Apache Camel K?

TODO

[NOTE]
====
A random note
====