++++
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
++++

== Introduction
Welcome to the Cloud Architecture Workshop. The workshop consists of several modules, which are independent of each other. You can choose which modules you want to take, and in which order you go through them.

==== Your user across all modules
Across all modules, at some point you will have to know your assigned user and password, as well as the URL of the OpenShift console. While all of this is presented to you in the individual modules, here it is, for your convenience:

++++
<div class="card">
  <div class="card-header">
++++
** OpenShift Console: *%openshift_cluster_console%*
** Username: *%user_name%*
** Password: *%user_password%*
++++
  </div>
</div>
<br>
++++

=== Get started
Before diving into a particular module, we recommend that you go through the workshop introduction module, to explore the technical and functional environment for this workshop.



++++
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Introduction to the Cloud Architecture Workshop.</h5>
        <p class="card-text">This chapter explains the technical and functional environment for this workshop, with a walkthrough of the existing implementation.<br>
        <span class="badge badge-pill badge-warning">#recommended</span>
        <span class="badge badge-pill badge-secondary">#overview</span>
        <span class="badge badge-pill badge-secondary">#hands-on</span>
        <span class="badge badge-pill badge-secondary">#explore</span></p>
        <a href="/workshop/workshop-introduction" class="btn btn-sm btn-info">Introduction &gt;</a>        
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Build new functionality with Change Data Capture</h5>
        <p class="card-text">
            In this module you discover how you can leverage Change Data Capture to build out new functionality with minimal impact on existing applications.<br>
        <span class="badge badge-pill badge-primary">#CDC</span>
        <span class="badge badge-pill badge-primary">#Kafka</span> 
        <span class="badge badge-pill badge-primary">#Debezium</span> 
        <span class="badge badge-pill badge-primary">#Camel-K</span> 
        <span class="badge badge-pill badge-primary">#Devspaces</span> 
        <span class="badge badge-pill badge-secondary">#hands-on</span>
        </p>
        <a href="/workshop/globex-cdc-into" class="btn btn-sm btn-info">Introduction &gt;</a>
        <a href="/workshop/globex-cdc-instructions" class="btn btn-sm btn-info">Instructions &gt;</a>
      </div>
    </div>
  </div>
</div>

++++


