++++
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
++++

== Introduction

++++
<br>
<h4><i>Discover the art of the possible.</i></h4>
<br>
++++

The Cloud Architecture Workshop showcases the art of the possible with Red Hat OpenShift and Red Hat Application Services.

This workshop consists of a number different modules, each highlighting a particular use case, development principle or technology. The modules have a common overarching story, revolving around the e-commerce site of a fictitious retail company (Globex). 

Globex has undergone significant modernization and they are keen to build on their application modernization efforts to rapidly build new functionalities. The workshop helps you navigate through each of these functionalities through a number of modules focusing on one particular use case.

The modules are independent from each other and can be taken in any combination or order. Each module consists of an introduction and an instructions section. 

* The *introduction* details the business problem we are trying to solve, possible solutions, a technical overview of the proposed solution and other background information. 
* The *instructions* provide details step-by-step details to guide you through the workshop.


Modules are provisioned on demand by you by using the *Workshop Deployer*.

You can access the *Workshop Deployer* by  https://workshop-deployer.%openshift_subdomain%[clicking here]

Go ahead! Choose your adventure! 
