++++
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
++++

== Introduction
Welcome to the Cloud Architecture Workshop. The workshop consists of several modules, which are independent of each other. You can choose which modules you want to take, and in which order you go through them.

=== Get started
Before diving into a particular module, we recommend that you go through the workshop introduction module, to explore the technical and functional environment for this workshop.



++++
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Introduction to the Cloud Architecture Workshop.</h5>
        <p class="card-text">This chapter explains the technical and functional environment for this workshop, with a walkthrough of the existing implementation.<br>
        <span class="badge badge-pill badge-warning">#recommended</span>
        <span class="badge badge-pill badge-secondary">#overview</span>
        <span class="badge badge-pill badge-secondary">#hands-on</span>
        <span class="badge badge-pill badge-secondary">#explore</span></p>
        <a href="/workshop/workshop-introduction" class="card-link">Introduction</a>        
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Build new functionality with Change Data Capture</h5>
        <p class="card-text">
            In this module you discover how you can leverage Change Data Capture to build out new functionality with minimal impact on existing applications.<br>
        <span class="badge badge-pill badge-primary">#CDC</span>
        <span class="badge badge-pill badge-primary">#Kafka</span> 
        <span class="badge badge-pill badge-primary">#Debezium</span> 
        <span class="badge badge-pill badge-primary">#Camel-K</span> 
        <span class="badge badge-pill badge-primary">#Devspaces</span> 
        <span class="badge badge-pill badge-secondary">#hands-on</span>
        </p>
        <a href="/workshop/cdc-module" class="card-link">Introduction</a>
        <a href="/workshop/cdc-module-instructions" class="card-link">Instructions</a>
      </div>
    </div>
  </div>
</div>

<br>

<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Launch new channels using Contract-First approach</h5>
        <p class="card-text">In this module you discover how Contract First Approach provides the right framework to acclerate launching new channels in a secure way.<br>
        <span class="badge badge-pill badge-primary">#API-Management</span> 
        <span class="badge badge-pill badge-primary">#Keycloak</span> 
        <span class="badge badge-pill badge-primary">#OIDC</span> 
        <span class="badge badge-pill badge-primary">#Apicurio</span> 
        <span class="badge badge-pill badge-primary">#Service-Registry</span> 
        <span class="badge badge-pill badge-primary">#3Scale</span> 
        <span class="badge badge-pill badge-primary">#Devspaces</span> 
        <span class="badge badge-pill badge-secondary">#hands-on</span>
        </p>
        <a href="/workshop/apim-module" class="card-link">Introduction</a>
        <a href="/workshop/apim-module-instructions" class="card-link">Instructions</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Build a service network to connect disparate services</h5>
        <p class="card-text">
            In this module you discover how to build a service network to connect disparate services using a secured layer 7 service network.<br>
        <span class="badge badge-pill badge-primary">#Skupper</span> 
        <span class="badge badge-pill badge-primary">#Service-Interconnect</span> 
        <span class="badge badge-pill badge-primary">#Application-Connectivity</span> 
        <span class="badge badge-pill badge-secondary">#hands-on</span>
        </p>
        <a href="/workshop/skupper-module" class="card-link">Introduction</a>
        <a href="/workshop/skupper-module-instructions" class="card-link">Instructions</a>
      </div>
    </div>
  </div>
</div>

<br>

<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Building a multi-channel support service for Globex customers</h5>
        <p class="card-text">
            In this module you will implement a pluggable multi-channel support service for Globex customers, integrating Globex Web, Slack and Discord.<br>
        <span class="badge badge-pill badge-primary">#Camel-K</span> 
        <span class="badge badge-pill badge-primary">#AMQ-Broker</span> 
        <span class="badge badge-pill badge-primary">#AMQ-Streams</span> 
        <span class="badge badge-pill badge-primary">#Kafka</span> 
        <span class="badge badge-pill badge-primary">#Data-Grid</span>  
        <span class="badge badge-pill badge-primary">#S3</span> 
        <span class="badge badge-pill badge-primary">#Data-Foundation</span> 
        <span class="badge badge-pill badge-secondary">#hands-on</span>
        </p>
        <a href="/workshop/camel-module" class="card-link">Introduction</a>
        <a href="/workshop/camel-module-instructions" class="card-link">Instructions</a>
      </div>
    </div>
  </div>
  
</div>
++++


