== Introduction
Welcome to the Cloud Architecture Workshop.

The workshop consists of several modules, which are independent of each other. You can choose which modules you want to take, and in which order you go through them.

=== Build new functionality with Change Data Capture +
In this module you discover how you can leverage Change Data Capture to build out new functionality with minimal impact on existing applications.

=== Launch new channels using Contract-First approach +
In this module you discover how Contract First Approach provides the right framework to acclerate launching new channels in a secure way.

=== Build  a service network to connect disparate services  +
In this module you discover how to build a service network to connect disparate services using a secured layer 7 service network.

=== Building a multi-channel support service for Globex customers  +
In this module you will implement a pluggable multi-channel support service for Globex customers, integrating Globex Web, Slack and Discord.


== Get started
Before diving into a particular module, we recommend that you go through the workshop introduction module, to explore the technical and functional environment for this workshop.


